<?php
	echo "<li><a class='navItem' href= 'index.php'>Home</a></li>";
	echo "<li><a class='navItem' href= 'topic.php'>Infomation</a></li>";
	echo "<li><a class='navItem' href= 'quiz.php'>Quiz</a></li>";
	echo "<li><a class='navItem' href= 'manage.php'>Manage</a></li>";
	echo "<li><a class='navItem' href= 'enhancements.html'>Features</a></li>";
	echo "<li><a class='navItem' href= 'enhancements2.html'>JavaScript</a></li>";
?>